image: tmaier/docker-compose:18

services:
  - docker:dind

stages:
  - test
  - package

before_script:
  - apk add --no-cache bash make git

test:
  stage: test
  script:
    - ./bin/test

package:
  stage: package
  script:
    - ./bin/build
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.zip
