image: tmaier/docker-compose:18

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - apk add --no-cache bash make git

build:
  stage: build
  script:
    - ./bin/build
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.zip
      - terraform-provider-conjur  # for next stage

test:
  stage: test
  script:
    - ./bin/test
