version: '3'
services:
  client:
    image: conjurinc/cli5
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL:
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
      CONJUR_SSL_CERTIFICATE:
    volumes:
      - $PWD/test:/test

  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform
      
    entrypoint: sleep infinity
    environment:
      CONJUR_APPLIANCE_URL:
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
      CONJUR_SSL_CERTIFICATE:
      TF_LOG: "${TF_LOG:-INFO}"
    working_dir: /src
    volumes:
      - $PWD:/src

  goreleaser:
    image: cyberark/goreleaser
    volumes:
      - .:/go/src/github.com/cyberark/terraform-provider-conjur
    working_dir: /go/src/github.com/cyberark/terraform-provider-conjur
